Repository vormkracht10/filament-2fa, pull requests merged in 2024-08, with the labels that each got.

#3 [Fix] Redirecting to wrong panel after challenge
  src/Http/Livewire/Auth/Login.php
  src/Http/Livewire/Auth/PasswordReset.php
  src/Http/Livewire/Auth/RequestPasswordReset.php
  src/Http/Responses/LoginResponse.php
  src/Http/Responses/TwoFactorChallengeViewResponse.php
  src/Http/Responses/TwoFactorLoginResponse.php
Labels: bug

#7 Customizable notification email mailable
  README.md
  resources/lang/en.json
  resources/lang/nl.json
  resources/views/emails/two-factor-code.blade.php
  src/Mail/TwoFactorCodeMail.php
  src/Notifications/SendOTP.php
Labels: enhancement

#8 PHPStan improvements
  .github/workflows/phpstan.yml
  phpstan.neon.dist
  src/Enums/TwoFactorType.php
  src/Http/Livewire/Auth/Login.php
  src/Http/Livewire/Auth/LoginTwoFactor.php
  src/Http/Livewire/Auth/PasswordConfirmation.php
  src/Http/Livewire/Auth/PasswordReset.php
  src/Http/Livewire/Auth/RequestPasswordReset.php
  src/Http/Responses/LoginResponse.php
  src/Http/Responses/TwoFactorChallengeViewResponse.php
  src/Listeners/SendTwoFactorCodeListener.php
  src/Notifications/SendOTP.php
  src/Pages/TwoFactor.php
  src/Traits/EnumArraySerializableTrait.php
  src/Traits/EnumNamesTrait.php
  src/Traits/EnumValuesTrait.php
  src/TwoFactorAuthServiceProvider.php
  tests/PHPStan/CustomPropertyReflection.php
  tests/PHPStan/UserPropertiesClassReflectionExtension.php
Labels: code improvement

#12 [Bug] Fix asset registration in provider
  resources/dist/filament-two-factor-auth.js
  src/TwoFactorAuthServiceProvider.php
Labels: bug

#16 [Bug fix] Invalid payload
  resources/views/two-factor.blade.php
Labels: bug

#18 Validate before pipeline to show error messages to users
  resources/dist/filament-2fa.css
  resources/dist/filament-two-factor-auth.js
  resources/views/auth/login-two-factor.blade.php
  src/Http/Livewire/Auth/Login.php
Labels: bug

#19 Use validate credentials before attempting to login
  src/Http/Livewire/Auth/Login.php
Labels: security

#20 [Bug fix] Resending otp code sometimes sends duplicates
  resources/views/auth/login-two-factor.blade.php
  resources/views/auth/password-reset.blade.php
  resources/views/auth/request-password-reset.blade.php
  src/Http/Livewire/Auth/Login.php
  src/Http/Livewire/Auth/LoginTwoFactor.php
Labels: bug

#22 [Feature] Allow register page customisation and fix tenancy issue
  README.md
  config/filament-two-factor-auth.php
  src/TwoFactorAuthPlugin.php
Labels: enhancement

#23 [Bug fix] OTP code should be required when challenging
  src/Http/Livewire/Auth/LoginTwoFactor.php
Labels: bug

#24 [Feature] Validate invalid OTP
  src/Pages/TwoFactor.php
Labels: enhancement
